 # Config for training ALAE on FFHQ at resolution 1024x1024

DATASET:
  SIZE: 300000
  FFHQ_SOURCE: /content/ALAE/datasets/forensics/tfrecords/records-r%02d.tfrecords
  
  PART_COUNT: 16
  PATH: /content/ALAE/datasets/forensics/tfrecords/train/records-r%02d.tfrecords.%03d
  
  PART_COUNT_TEST: 2
  PATH_TEST: /content/ALAE/datasets/forensics/tfrecords/test/records-r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 5
  FLIP_IMAGES: False
  SAMPLES_PATH: /content/drive/My Drive/GAN/Forensics/test/benign
MODEL:
  LATENT_SPACE_SIZE: 32
  LAYER_COUNT: 4
  MAX_CHANNEL_COUNT: 256
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 4
  CHANNELS: 3
OUTPUT_DIR: /content/drive/My Drive/GAN/Forensics/results_ALAE
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 16
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 300
  LOD_2_BATCH_8GPU: [128, 128, 128,   64]
  LOD_2_BATCH_4GPU: [128, 128, 128,   64]
  LOD_2_BATCH_2GPU: [128, 128, 128,   64]
  LOD_2_BATCH_1GPU: [128, 128, 128,   64]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0008]